import '../styles/globals.css';
import Head from 'next/head';
import { useEffect } from 'react';
import { useRouter } from 'next/router';

/**
 * Custom App component for global configuration
 * 
 * @param {Object} props
 * @param {React.ComponentType} props.Component - The active page component
 * @param {Object} props.pageProps - Props generated by Next.js for the page
 * @returns {JSX.Element}
 */
export default function MyApp({ Component, pageProps }) {
  const router = useRouter();
  
  // Track page views (in a real app, this would connect to an analytics service)
  useEffect(() => {
    const handleRouteChange = (url) => {
      // In a real app, this would send analytics data
      console.log(`Page view: ${url}`);
    };
    
    router.events.on('routeChangeComplete', handleRouteChange);
    
    return () => {
      router.events.off('routeChangeComplete', handleRouteChange);
    };
  }, [router.events]);
  
  return (
    <>
      <Head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="description" content="Document Search App - Search through your documents with powerful filters and contextual results" />
        <meta name="theme-color" content="#10B981" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Component {...pageProps} />
    </>
  );
}
